name: Bug report
description: Report incorrect behavior or crashes in bsky2masto
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened vs what you expected.
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Command used
      placeholder: bsky2masto --actor ... --verify
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - OS:
        - Python version:
        - Install method (pipx/pip/uvx/source):
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant output. Remove personal data.
      render: shell

  - type: textarea
    id: sample
    attributes:
      label: Sample profile text or input (sanitized)
      description: Optional but very helpful for parser bugs.
